on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt Libraries
        run: |
          sudo apt update
          sudo apt install qtchooser *qt6*
          qtchooser -install qt6 $(which qmake6)
          sudo mv ~/.config/qtchooser/qt6.conf /usr/share/qtchooser/qt6.conf
          sudo mkdir -p /usr/lib/$(uname -p)-linux-gnu/qt-default/qtchooser
          sudo mv /usr/share/qtchooser/qt6.conf /usr/lib/$(uname -p)-linux-gnu/qt-default/qtchooser/default.conf
      - name: Build
        run: |
          mkdir build && cd build
          qmake .. && make
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
            build/analytics-app
