on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Qt Libraries
        run: |
          sudo apt update
          sudo apt install libgl1-mesa-dev qtchooser *qt6*
          qtchooser -install qt6 $(which qmake6)
          sudo mv ~/.config/qtchooser/qt6.conf /usr/share/qtchooser/qt6.conf
          sudo mkdir -p /usr/lib/$(uname -p)-linux-gnu/qt-default/qtchooser
          sudo mv /usr/share/qtchooser/qt6.conf /usr/lib/$(uname -p)-linux-gnu/qt-default/qtchooser/default.conf
      - name: Build
        run: |
          mkdir build && cd build
          qmake .. && make -j
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: |
            build/analytics-app
      - name: Publish to server
        env:
          SSHPASS: ${{ secrets.deploy_server_password }}
          DEPLOY_HOST: ${{ secrets.deploy_server_host_name }}
          DEPLOY_PATH: ${{ secrets.deploy_server_path }}
        run: |
            sudo apt install sshpass
            sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P 49170 build/analytics-app root@$DEPLOY_HOST:$DEPLOY_PATH
